### ISSUE TITLE
Add reset_maintenance Service

### ISSUE THREAD

**Issue by rafael-zilberman** [rafael-zilberman/device-maintenance-monitor-custom-component#14]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rafael-zilberman/device-maintenance-monitor-custom-component/labels/enhancement).

### Is your feature request related to a problem? Please describe.

Currently, resetting the maintenance data must be done manually through the UI. This can be cumbersome for users who want to automate the process or include it in scripts and automations.

### Describe the solution you'd like

Implement a `reset_maintenance` service that allows users to programmatically reset the maintenance data for a specified device. This service should be callable within Home Assistant scripts and automations.

### Additional context

The `reset_maintenance` service should accept parameters to specify the target devices or entities whose maintenance data should be reset. This would enable users to automate maintenance workflows and integrate the reset functionality into their broader automation setups.

Example usage in an automation:

```yaml
automation:
  - alias: Reset AC Maintenance
    trigger:
      platform: state
      entity_id: binary_sensor.ac_maintenance_needed
      to: 'on'
    action:
      service: device_maintenance_monitor.reset_maintenance
      data:
        entity_id: binary_sensor.ac_maintenance_needed
    action:
      service: device_maintenance_monitor.reset_maintenance
      data:
        device_id: 8de7e270b1f19dd685b80b4d9fa2e257
```

This feature will enhance the flexibility and usability of the integration by allowing maintenance resets to be automated and integrated into Home Assistant's extensive automation capabilities.
