### ISSUE TITLE
Use alert Integration of Home Assistant to Notify About Maintenance

### ISSUE THREAD

**Issue by rafael-zilberman** [rafael-zilberman/device-maintenance-monitor-custom-component#15]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rafael-zilberman/device-maintenance-monitor-custom-component/labels/enhancement).

### Is your feature request related to a problem? Please describe.

Currently, users need to create custom automations to get notifications about maintenance needs. This can be cumbersome and requires additional setup steps.

### Describe the solution you'd like

Integrate the `alert` component of Home Assistant directly into the Device Maintenance Monitor. This will allow users to receive notifications about maintenance needs without having to create custom automations.

### Additional context

The alert integration provides a straightforward way to set up notifications that repeat until acknowledged. This can ensure that maintenance reminders are not missed. Here is an example configuration:

```yaml
alert:
  device_maintenance_needed:
    name: "Device Maintenance Needed"
    done_message: "Maintenance has been performed"
    entity_id: binary_sensor.device_maintenance_needed
    state: "on"
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_your_device
```

Integrating this directly into the Device Maintenance Monitor would streamline the notification process and improve the user experience by making maintenance alerts more accessible and easier to manage.
